### ISSUE TITLE
怀疑是数据问题引起的扩展出core

### ISSUE THREAD

**Issue by yyz26371945** [swoole/ext-serialize#9]
更新到0.1.2之后，刚开始两个月都很正常，但是最近一直频繁出core，初步猜测是数据问题，这个是出错堆栈，你可以先看看
![image](https://user-images.githubusercontent.com/20291334/26921701-6bee158c-4c6f-11e7-89b1-7c2b340c5cf6.png)

我这两天跑下全量数据，看看能不能找到引起问题的数据

**Comment by GXhua** [comment]
堆栈的#2  能打印下这个序列化对象吗

**Comment by yyz26371945** [comment]
我明天会跑数据，看下到底是哪个数据引起的，到时候给你打印一下

**Comment by GXhua** [comment]
好的

**Comment by yyz26371945** [comment]
我这边线下跑了全量数据没有复现出来core，但是线上只要使用序列化方法，二十多秒就会有一个core出来
然后我替换成0.1.1版本，生成的堆栈如下：
![image](https://user-images.githubusercontent.com/20291334/27032944-a952cae8-4fa9-11e7-9273-e6fa748ceac8.png)

然后我把opcache关掉之后，就再也没有发生core了，但是线下不管有没有开启和关闭opcache，都没有复现

**Comment by GXhua** [comment]
额。。。难道和opcache有关？你们是怎么用swoole serialize的

**Comment by yyz26371945** [comment]
我们的做法就是把一个object通过调用swoole_serialize函数序列化之后存入apcu里面，然后用的时候再拿出来swoole_unserialize
